package com.atakmap.android.xv.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM sealing against a **hardware-backed, non-exportable** key
 * held in the Android Keystore. This is the envelope that wraps the
 * [com.atakmap.android.xv.transport.multicast.MeshKeyVault] blob before
 * it is written to disk, so the per-channel voice keys never persist as
 * plaintext or JSON — only ciphertext that can be decrypted on *this*
 * device, by *this* app, and only while the keystore key still exists.
 *
 * The keystore key itself never leaves the TEE/StrongBox: [seal] and
 * [open] hand plaintext/ciphertext to the keystore and get the transform
 * back, but the raw AES key material is unreadable to us and to anyone
 * who pulls the ciphertext off the filesystem. [wipe] deletes the
 * keystore key, which cryptographically shreds every blob it ever
 * produced — the basis for the panic "wipe mesh keys" action.
 *
 * Sealed blob layout (all ints big-endian):
 *
 *     [ byte  version = 1        ]
 *     [ byte  ivLen (== 12)      ]
 *     [ bytes iv                 ]
 *     [ bytes ciphertext + tag   ]
 *
 * The IV is generated by the keystore on every [seal] (we must NOT
 * supply one for an AndroidKeyStore GCM key) and read back off the
 * initialized cipher, so every seal is fresh even for identical input.
 *
 * minSdk is 26; AndroidKeyStore AES-GCM has been available since API 23,
 * so no version gate is needed here.
 */
object KeystoreSecretBox {
    private const val ANDROID_KEYSTORE = "AndroidKeyStore"

    // Alias for the mesh-key-vault wrapping key. Stable across plugin
    // loads so a sealed blob written last session decrypts this session.
    private const val KEY_ALIAS = "xv_mesh_key_vault_v1"

    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val KEY_SIZE_BITS = 256
    private const val GCM_TAG_BITS = 128
    private const val GCM_IV_BYTES = 12
    private const val VERSION: Byte = 1

    /** Thrown when a blob can't be opened (missing key, tamper, malformed). */
    class SealException(message: String, cause: Throwable? = null) : GeneralSecurityException(message, cause)

    /**
     * Seal [plaintext] under the keystore key, creating that key on first
     * use. Returns a self-describing blob suitable for [open].
     */
    fun seal(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv
        require(iv.size == GCM_IV_BYTES) { "unexpected GCM IV length ${iv.size}" }
        val ct = cipher.doFinal(plaintext)
        return ByteBuffer.allocate(2 + iv.size + ct.size)
            .order(ByteOrder.BIG_ENDIAN)
            .put(VERSION)
            .put(iv.size.toByte())
            .put(iv)
            .put(ct)
            .array()
    }

    /**
     * Reverse of [seal]. Throws [SealException] if the keystore key is
     * gone (e.g. after [wipe] or an OS-level key reset), the blob is
     * malformed, or the GCM tag fails to verify (tamper / wrong device).
     */
    fun open(blob: ByteArray): ByteArray {
        val iv: ByteArray
        val ct: ByteArray
        try {
            val buf = ByteBuffer.wrap(blob).order(ByteOrder.BIG_ENDIAN)
            val version = buf.get()
            if (version != VERSION) throw SealException("unsupported sealed-box version $version")
            val ivLen = buf.get().toInt() and 0xFF
            if (ivLen != GCM_IV_BYTES) throw SealException("bad IV length $ivLen")
            if (buf.remaining() < ivLen) throw SealException("truncated: IV")
            iv = ByteArray(ivLen).also { buf.get(it) }
            ct = ByteArray(buf.remaining()).also { buf.get(it) }
        } catch (e: SealException) {
            throw e
        } catch (t: Throwable) {
            throw SealException("malformed sealed box: ${t.message}", t)
        }

        val key = existingKey() ?: throw SealException("mesh key-vault keystore entry is absent")
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
            cipher.doFinal(ct)
        } catch (t: Throwable) {
            // AEADBadTagException, key-invalidated, provider errors — all
            // collapse to "can't open" so callers fail closed.
            throw SealException("unable to open sealed box: ${t.message}", t)
        }
    }

    /** True once a keystore wrapping key exists (i.e. something was sealed). */
    fun hasKey(): Boolean = existingKey() != null

    /**
     * Delete the keystore wrapping key. Every blob it produced becomes
     * permanently undecryptable — the cryptographic-shred half of the
     * panic wipe. Idempotent; safe to call when no key exists.
     */
    fun wipe() {
        try {
            keystore().deleteEntry(KEY_ALIAS)
        } catch (_: Throwable) {
            // Nothing to delete / provider hiccup — the caller's intent
            // (no usable key) is satisfied either way.
        }
    }

    private fun keystore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private fun existingKey(): SecretKey? =
        try {
            (keystore().getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.secretKey
        } catch (_: Throwable) {
            null
        }

    private fun getOrCreateKey(): SecretKey {
        existingKey()?.let { return it }
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        gen.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                // No user-authentication requirement: the vault must be
                // openable headless on plugin load (device may be locked
                // in a pocket). Confidentiality comes from the key being
                // non-exportable and scoped to this app + device.
                .build(),
        )
        return gen.generateKey()
    }
}
